tasks:
  - name: start-app
    before: |
      nvm install --lts
      npm install -g aws-cdk
    init: |
      python setup/git_hooks.py
      python setup/dev.py
      npm install
      gp sync-done install
    command: npm start
  - name: test-watch
    init: gp sync-await install
    command: npm run test
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
